name: pokezero
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py39hf3d152e_1
  - cffi=1.14.5=py39he32792d_0
  - cpuonly=1.0=0
  - future=0.18.2=py39hf3d152e_3
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgomp=9.3.0=h2828fa1_18
  - liblapack=3.9.0=8_mkl
  - libstdcxx-ng=9.3.0=h6de172a_18
  - llvm-openmp=11.0.1=h4bd325d_0
  - mkl=2020.4=h726a3e6_304
  - ncurses=6.2=h58526e2_4
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.20.1=py39hdbf815f_0
  - openssl=1.1.1j=h7f98852_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - python=3.9.2=hffdb5ce_0_cpython
  - python_abi=3.9=1_cp39
  - pytorch=1.7.1=cpu_py39h714fb45_2
  - readline=8.0=he28a2e2_2
  - setuptools=49.6.0=py39hf3d152e_3
  - sqlite=3.34.0=h74cdb3f_0
  - tk=8.6.10=h21135ba_1
  - typing_extensions=3.7.4.3=py_0
  - tzdata=2021a=he74cb21_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - pip:
    - aiologger==0.6.0
    - beautifulsoup4==4.9.3
    - chardet==4.0.0
    - cloudpickle==1.6.0
    - gym==0.18.0
    - idna==2.10
    - orjson==3.5.0
    - pillow==7.2.0
    - poke-env==0.4.7
    - pyglet==1.5.0
    - requests==2.25.1
    - scipy==1.6.1
    - soupsieve==2.2
    - tabulate==0.8.9
    - urllib3==1.26.3
    - websockets==8.1
prefix: /home/sudarshan/anaconda3/envs/pokezero
